path:
  data_dir_path: data
  image_dir: chatbot_images
  embedding_dir: storages
  item_cate_file: filter_result.csv
  compose_embedding_file: hash_apparels_chatbot.pkl
  retrieve_embedding_file: embedding.npy
  encoder_o_trained: data/checkpoints/11_26_23/encoder_o_best_11_26.pt
  core_trained: data/checkpoints/11_26_23/core_best_11_26.pt

recommend:
  cates: ["top", "bottom", "outerwear", "bag", "footwear"]
  chosen_cates_first: ["top", "outerwear", "bottom", "top"]
  num_outfits: 4
  top_k: 7
  num_recommends_for_composition: 10
  get_composed_recommendation: True

net:
  dim: 128
  use_outfit_semantic: True
  outfit_semantic_dim: 512
  pairwise_weight: 1.0
  outfit_semantic_weight: 1.5
  hash_types: 3
  scale_tanh: True
  without_binary: False
  binary01: False
  score_type_selection: "binary"
  feature_type_selection: "visual"  
